# Prerequisites:
# 1. In Azure Portal, open your Web App and click "Get publish profile" to download the XML file.
# 2. In your GitHub repository, go to Settings → Secrets → Actions, and create a secret:
#    Name: AZURE_WEBAPP_PUBLISH_PROFILE
#    Value: (Paste the entire XML content from the publish profile.)
# 3. (Optional) To use Service Principal authentication via azure/login, create a secret:
#    Name: AZURE_CREDENTIALS
#    Value: (Run `az ad sp create-for-rbac --sdk-auth` and paste the JSON output.)
#
# Usage:
# - Push to `main` or manually trigger via the Actions tab.
# - The workflow will build, test, publish your Web API, and deploy to Azure automatically.


name: CI/CD – API

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: bvm-prod-ccan-api
  AZURE_WEBAPP_PACKAGE_PATH: publish           # publish folder under the project
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: src/BVM.WebApi       # project folder relative to repo root

concurrency:
  group: CI-CD-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 'CI: Build, Test & Publish'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-packages-${{ hashFiles('**/*.csproj') }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal

      - name: Publish artifacts
        run: |
          dotnet publish \
            --configuration ${{ env.CONFIGURATION }} \
            --no-build \
            --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  cd:
    name: 'CD: Deploy to Azure'
    runs-on: ubuntu-latest
    needs: ci
    if: success()
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.WORKING_DIRECTORY }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
